"""Creacion tabla empleado

Revision ID: 53f51556825d
Revises: 
Create Date: 2026-02-13 10:22:01.027432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f51556825d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleados',
    sa.Column('idEmpleado', sa.Integer(), nullable=False, auto_increment=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('departamento', sa.String(length=100), nullable=False),
    sa.Column('sueldo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('idEmpleado')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empleados')
    # ### end Alembic commands ###
